# Generated by Django 2.1.2 on 2019-04-10 22:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=30)),
                ('date_birth', models.DateField(blank=True, default=datetime.date.today)),
                ('preferred_genre', models.CharField(choices=[('comedy', 'Comedy'), ('horror', 'Horror'), ('all', 'All')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
