# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_genre',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('horror', 'Horror'), ('all', 'All')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
