# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('movie_logo', models.FileField(upload_to=b'')),
                ('liked', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
