# Generated by Django 2.2 on 2019-05-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_cluster_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_name',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
