# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20181029_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.FileField(upload_to=b''),
        ),
    ]
