# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='liked',
        ),
    ]
