# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
