# Generated by Django 2.2 on 2019-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190503_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vectors',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
