# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_movie_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
