# Generated by Django 2.2 on 2019-05-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_review_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='size',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
