# Generated by Django 2.1.2 on 2019-02-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
