# Generated by Django 2.1.2 on 2019-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20190226_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
