# Generated by Django 2.1.2 on 2019-03-30 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=models.CharField(default='action', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(default='en', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(default='overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=3, default=75.456, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.FileField(default='poster', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, default=5.5, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
