# Generated by Django 2.1.2 on 2019-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0003_auto_20190330_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(default='path', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.CharField(max_length=30),
        ),
    ]
