# Generated by Django 2.1.2 on 2019-04-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0005_auto_20190402_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_ids',
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(),
        ),
    ]
