# Generated by Django 2.1.2 on 2019-04-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0006_auto_20190406_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12.2, max_digits=6),
            preserve_default=False,
        ),
    ]
