# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 12:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190325_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date_month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiry_date_year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(2019)]),
        ),
    ]
